/**/
setDay(1, { author: 'Ulrich Bär', license: 'CC0', url3mf: 'Icosahedron/Icosahedron.3mf', urlImg: 'Icosahedron/Icosahedron.png', urlScad: 'Icosahedron/Icosahedron.scad' });
setDay(2, { author: 'Ulrich Bär', license: 'CC0', urlImg: 'Octahedron/Octahedron.png', urlScad: 'Octahedron/Octahedron.scad' });
setDay(3, { author: 'Ulrich Bär', license: 'CC0', url3mf: 'Tower/Tower.3mf', urlImg: 'Tower/Tower.png', urlScad: 'Tower/Tower.scad' });
setDay(4, { author: 'Ulrich Bär', license: 'CC0', urlImg: 'Polycube/Polycube.png', urlScad: 'Polycube/Polycube.scad' });
setDay(5, { author: 'Ulrich Bär', license: 'CC0', urlImg: 'Ornaments/Ornaments-1.png', url3mf: 'Ornaments/Ornaments.3mf', urlScad: 'Ornaments/Ornaments.scad' });
setDay(6, { author: 'Ulrich Bär', license: 'CC0', url3mf: 'Star/Star.3mf', urlImg: 'Star/Star.png', urlScad: 'Star/Star.scad' });
setDay(7, { author: 'Ulrich Bär', license: 'CC0', urlImg: 'Polyhedron/Polyhedron.gif', urlScad: 'Polyhedron/Polyhedron.scad' });
setDay(8, { author: 'Ulrich Bär', license: 'CC0', url3mf: 'Honeycomb/Honeycomb.3mf', urlImg: 'Honeycomb/Honeycomb.png', urlScad: 'Honeycomb/Honeycomb.scad' });
setDay(9, { author: 'Ulrich Bär', license: 'CC0', url3mf: 'Cone/Cone.3mf', urlImg: 'Cone/Cone.png', urlScad: 'Cone/Cone.scad' });
setDay(10, { author: 'Ulrich Bär', license: 'CC0', url3mf: 'Dodecahedron/Dodecahedron.3mf', urlImg: 'Dodecahedron/Dodecahedron.png', urlScad: 'Dodecahedron/Dodecahedron.scad' });
setDay(11, { author: 'Ryan A. Colyer', license: 'CC0', urlScad: 'Snowballs/Snowballs.scad' });
setDay(12, { author: 'Ulrich Bär', license: 'CC0', url3mf: 'ColorCube/ColorCube.3mf', urlImg: 'ColorCube/ColorCube.gif', urlScad: 'ColorCube/ColorCube.scad' });
setDay(13, { author: 'Ulrich Bär', license: 'CC0', url3mf: 'Conjunctions/Conjunctions.3mf', urlImg: 'Conjunctions/Conjunctions.png', urlScad: 'Conjunctions/Conjunctions.scad' });
setDay(14, { author: 'Ulrich Bär', license: 'CC0', url3mf: 'Maze/Maze.3mf', urlImg: 'Maze/Maze.png', urlScad: 'Maze/Maze.scad' });
setDay(15, { author: 'Ulrich Bär', license: 'CC0', urlImg: 'Hayball/hayball.png', urlScad: 'Hayball/hayball.scad' });
setDay(16, { author: 'Ulrich Bär', license: 'CC0', url3mf: 'Oloid/Oloid.3mf', urlImg: 'Oloid/Oloid.png', urlScad: 'Oloid/Oloid.scad' });
setDay(17, { author: 'Ulrich Bär', license: 'CC0', urlImg: 'Neuron/Neuron.png', urlScad: 'Neuron/Neuron.scad' });
setDay(18, { author: 'Ryan A. Colyer', license: 'CC0', url3mf: 'KeyHolder/KeyHolder.3mf', urlImg: 'KeyHolder/KeyHolder.png', urlScad: 'KeyHolder/KeyHolder.scad' });
setDay(19, { author: 'Ulrich Bär', license: 'CC0', url3mf: 'Zen/Zen.3mf', urlImg: 'Zen/Zen.png', urlScad: 'Zen/Zen.scad' });
setDay(20, { author: 'Ulrich Bär', license: 'CC0', url3mf: 'Tree/Tree.3mf', urlImg: 'Tree/Tree.png', urlScad: 'Tree/Tree.scad' });
